### ISSUE TITLE
the difference between the three db files 

### ISSUE THREAD

**Issue by adminFlower** [cmu-pasta/linux-kernel-enriched-corpus#1]
Could you please tell me what is the difference between the three db files (ci-qemu-upstream-corpus.db,corpus.db and enriched-ci-qemu-upstream-corpus.db)?

**Comment by oswalpalash** [comment]
Hello, a detailed update on the results will be shared in the syzkaller mailing list. 
I've added a brief description of the three on the README through [ 275af2fcd941ad3a94b0d41a915d5cc4ae7b8ebf ](https://github.com/cmu-pasta/linux-kernel-enriched-corpus/commit/275af2fcd941ad3a94b0d41a915d5cc4ae7b8ebf)
