### ISSUE TITLE
Disappearing 'enriched-ci-qemu-upstream-corpus.db'

### ISSUE THREAD

**Issue by now4yreal** [cmu-pasta/linux-kernel-enriched-corpus#2]
Hello, thank you very much for your work. I am a beginner in this area, and I wanted to ask why you removed 'enriched-ci-qemu-upstream-corpus.db' from the repository. Thank you.

**Comment by oswalpalash** [comment]
It’s under releases https://github.com/cmu-pasta/linux-kernel-enriched-corpus/releases
